# name: Render PCB Images
# on:
#   push:
# jobs:
#   render-images:
#     name: render-images
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v4

#       - name: render pcb images
#         uses: linalinn/kicad-render@main
#         with:
#           pcb_file: hw/Zelvicka.kicad_pcb
#           output_path: ${{ github.workspace }}/images
#           animation: gif

#       - name: Setup Pages
#         if: github.ref == 'refs/heads/main'
#         uses: actions/configure-pages@v3

#       - name: Upload Artifact
#         if: github.ref == 'refs/heads/main'
#         uses: actions/upload-pages-artifact@v1
#         with:
#           path: "images"

#   deploy-pages:
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     needs: render-images

#     permissions:
#       pages: write
#       id-token: write

#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v2